### ISSUE TITLE
Variable substitution for default values

### ISSUE THREAD

**Issue by laserlemon** [bkeepers/envy#12]
From the README:

``` ruby
desc "The host name where the API is served from."
string :api_host_name, :default => "api.$HOST_NAME"
```

The `api.$HOST_NAME` notation wasn't immediately obvious to me. I'm assuming that this notation makes sense in the context of Bash scripting but maybe it's worth considering a more Ruby-centric approach:

``` ruby
desc "The host name where the API is served from."
string :api_host_name, :default => "api.%{host_name}"
```

a la Ruby's [`String#%`](http://www.ruby-doc.org/core-2.1.2/String.html#method-i-25) method.

**Comment by bkeepers** [comment]
For now you can use a lambda and ruby string interpolation:

```ruby
string :app_host
string :api_host_name, default: -> { "api.#{app_host}" }
```
