### ISSUE TITLE
Future Plans?

### ISSUE THREAD

**Issue by asadakbar** [bkeepers/envy#24]
Saw your pull request for this on [dotenv](https://github.com/bkeepers/dotenv/pull/131). This would be super helpful if you ever get some time to polish it off. Anything left you are looking for help with?

**Comment by bkeepers** [comment]
Hey @asadakbar, sorry for the radio silence. I just wanted to give you a heads up that I'm reviving this project. I still don't have  a gem published yet, but I'll be deploying it in production on one of my apps today and working to get a first release out soon. There are directions in the README for installing it via GitHub.

**Comment by asadakbar** [comment]
Great! Looking forward to it.
